### ISSUE TITLE
Storage files

### ISSUE THREAD

**Issue by owlysk** [hschneider/neutralino-build-scripts#2]
Hi,
did you test neutralino storage feature?
I have app, which is using [storage feature](https://neutralino.js.org/docs/api/storage). 
App expected to write to `.storage` directory in root, but I am not sure, if it possible in MacOS app bundle.
```
── xxxx.app
   └── Contents
       ├── Info.plist
       ├── MacOS
       │   ├── bootstrap
       │   └── main
       └── Resources
           ├── app.icns
           ├── icon.icns
           ├── resources
           │   ├── icons
           │   ├── js
           │   └── lib
           ├── resources.neu
           └── .storage
               ├── cache.neustorage    <--- can't write to this file
               └── setting.neustorage  <--- can't write to this file

```
Thanks for any suggestion

**Comment by hschneider** [comment]
I never used .storage, but its location is correct. 

/Contents/Resources is allowed to write. If you put it in /Contents/MacOS, then the app's signature and notarization will be broken, because macOS Gatekeeper detects a manipulated app bundle.

You can send me as simple storage test app, I can execute it here on my Mac.

**Comment by owlysk** [comment]
Thanks for response. Please have a look at [test repo](https://github.com/owlysk/neustoragetest)
After I click to "writeToStorage" I will get a error.

When I am running this test app as script file (standard release output of neutralino) "writeToStorage" will work.
I don't know, what I am doing wrong.

Do you have any idea?

**Comment by hschneider** [comment]
Sorry, I can test a ready built macOS app, but I cannot debug your code ...
However, maybe calling the async function directly from an onClick handler has some side-effects.

Try this:

```js
// onclick="handleStorage()"

function handleStorage() {
  (async () => {
     await writeStorage();
  })();
}

```

**Comment by owlysk** [comment]
Hi, here is my test in dist bundle:
[test.zip](https://github.com/hschneider/neutralino-build-scripts/files/13686787/test.zip)
I added function to write file, which ends with error too. I tried your suggestion, but this is not working either.
I think, issue is caused by file location. I tried to edit `bootstrap` file to:
```
exec "${MACOS}/main" --path="${CONTENTS}/Resources" --enable-extensions=true --user-data-dir="${CONTENTS}/Resource"
```
but still have no luck.
Argument `--window-enable-inspector=<true|false>` is not working as well.

Can you please test bundle?
Thanks

**Comment by hschneider** [comment]
The ZIP contains no macOS app bundle.

**Comment by owlysk** [comment]
Here you go 
[mac_x64.zip](https://github.com/hschneider/neutralino-build-scripts/files/13687363/mac_x64.zip)

**Comment by hschneider** [comment]
Works as expected :-)

https://app.screencast.com/BO6O1xGSA3UTR

**Comment by owlysk** [comment]
That's weird. Obviously I am doing something wrong :D
So, what did you exactly do after download?

**Comment by hschneider** [comment]
I've just reset the quarantine attribute, used by macOS Gatekeeper to lock downloads from the internet:

```bash
sudo xattr -d -r com.apple.quarantine APPNAME.app
```

Which error do you get in the app's dev console?

**Comment by owlysk** [comment]
My steps:
1. Download zip file from github
2. Open `downloads` folder in finder app
3. Double click on app to open
4. Shows security dialog, closing dialog
5. Going to setting > security, to allow opening app
6. App opened, 
7. Clicked to writeToStorage link
8. Getting error - screenshot.

Am I doing something wrong?

 ![Snímka obrazovky zo dňa 2023-12-15 21-01-01](https://github.com/hschneider/neutralino-build-scripts/assets/79711410/cf6554cb-fe88-457e-a9ab-426cc64500c4)

**Comment by hschneider** [comment]
Gatekeeper locks the app and therefore write access to Contents/Resources, if you do not clear the quarantine flag.
Confirming the security dialog does launch the app, but in a sandbox without write permissions.

You can verify this by issuing this command on your app in its current state (forced to open in Finder, but still quarantined):

```bash

xattr -r /Users/hschneider/Downloads/mac_x64/neustoragetest.app 

/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/MacOS/bootstrap: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/MacOS/main: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/MacOS: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/icon.icns: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/index.html: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/styles.css: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/js/neutralino.js: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/js/index.js: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/js/main.js: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/js: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/.storage/setting.neustorage: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/.storage: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/icons/logo.gif: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/icons/appIcon.png: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/icons/trayIcon.png: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/icons: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources/resources.neu: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Resources: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents/Info.plist: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app/Contents: com.apple.quarantine
/Users/hschneider/Downloads/mac_x64/neustoragetest.app: com.apple.provenance
/Users/hschneider/Downloads/mac_x64/neustoragetest.app: com.apple.quarantine
```

As you see, the quarantine flags are still there.

Use the xattr command right after download to clear all flags, **before** you open the app.

All this won't be an issue if the app has been signed and notarized by Apple.

**Comment by hschneider** [comment]
Signed and notarized version here:

https://www.dropbox.com/scl/fi/x5iifu2fct8tyththdksl/neustoragetest.dmg.zip?rlkey=22r1e584lue6jui43e5zg9gf6&dl=0

****

**Comment by owlysk** [comment]
Hi, 
you are right. After I run `sudo xattr -d -r com.apple.quarantine APPNAME.app` app is finally working.
I figure out, that if I move app from `Downloads` directory, app works as expected. I think that solved my issue :D

I'm sorry, I am not using Mac OS very often, so for me, this all are new informations O:-)
Thanks for your help
